[versions]
junit-bom = "6.0.2"
maven-publish = "0.36.0"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }